# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tzM6IqM-VkZHlku0xta6sKcaLFmROcvj
"""

from telethon import TelegramClient, events

# Ваші дані
api_id = 34771076
api_hash = 'f697607767753e21c302bf6b1fee0602'

# ЗАМІНІТЬ ТУТ: слово, яке треба шукати
TARGET_WORD = ['центр', 'печерськ', 'липки']

# ЗАМІНІТЬ ТУТ: список каналів, які треба слухати (юзернейми без @)
WATCH_CHANNELS = ['waypoint_ua', 'kyiv_monitor1', 'war_monitor', 'kyivnebomonitoring' ]

client = TelegramClient('my_new_session', api_id, api_hash)

@client.on(events.NewMessage(chats=WATCH_CHANNELS))
async def handler(event):
    message_text = event.message.text or ''

    if TARGET_WORD.lower() in message_text.lower():
        await client.send_message('me', f'🔔 Знайдено слово у каналі @{event.chat.username}:\n\n{message_text}')

print("Бот запускається...")
await client.start()
print("Бот працює і слухає канали!")
await client.run_until_disconnected()

!pip install telethon